# -*- coding: utf-8 -*-
"""01_variables.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1msbrmLt_dqwlu10YfNNeRRgSBRxRfFZf
"""

### Variables ###

my_string_variable= "My String variable"
print(my_string_variable)

my_int_variable = 5
print(my_int_variable)

my_int_to_str__variable = str(my_int_variable)
print(my_int_to_str__variable)
print(type(my_int_to_str__variable))

my_bool_variable= False
print(my_bool_variable)

# concatenación de variables en un print
print(my_string_variable, my_int_to_str__variable, my_bool_variable)
print("este es el valor de;",my_bool_variable)

# algunas funciones del sistema
print(len(my_string_variable))

# variables en una sola linea. ¡Cuidado con abusar de esta sintaxis!
name, surname, alias, age = "Jenni", "Cubillo Aguilar", "lupe", 35
print("me llamo;", name, surname, "mi edad es;",
      age, ". Y mi alias es;", alias)

# Inputs # solitar informacion por teclado
name = input(' ¿Cual es tu nombre? ')
age = input ('¿Cuantos años tienes? ')
print(name)
print(age)

# Cambiamos su tipo
name = 35
age = "jenni"
print(name)
print(age)

# ¿Forzamos el tipo?
address: str = "Mi dirección"
address = True
address = 5
address = 1.2
print(type(address))

